### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 197 but got size 196 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by Laqcey** [XinyiYing/LESPS#10]
你好，在训练过程中，epoch在30-50期间（每一次训练在哪个epoch报错会变动）会报错：
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 197 but got size 196 for tensor number 1 in the list.

报错位置为model_DNANet.py的forward函数的第三行        x0_1 = self.conv0_1(torch.cat([x0_0, self.up(x1_0)], 1))

经过打印，发现报错时x0_0的size为[1, 16, 197, 320]，self.up(x1_0)的size为[1, 32, 196, 320]，请问我应该怎么解决呢？期待你的回复。

**Comment by XinyiYing** [comment]
See https://github.com/XinyiYing/LESPS/issues/8#issuecomment-1837698309

**Comment by superli6** [comment]
> 参见 [#8（评论）](https://github.com/XinyiYing/LESPS/issues/8#issuecomment-1837698309)

Hello, you made the relevant settings in the code. How can I make them take effect? Because when I run test.py directly, I still encounter tensor mismatch issues. How can I solve this?
torch.Size([1, 16, 685, 864])
torch.Size([1, 32, 684, 864])

**Comment by XinyiYing** [comment]
非常抱歉代码中的bug给大家带来的不便，上下不匹配的维度已在代码中修复，详情可参考https://github.com/XinyiYing/LESPS/issues/8#issuecomment-1837698309
