### ISSUE TITLE
 raise TypeError('img should be PIL Image. Got {}'.format(type(img))) TypeError: img should be PIL Image. Got <class 'torch.Tensor'>

### ISSUE THREAD

**Issue by Reginaii** [XinyiYing/LESPS#13]
您好，在复现 ALCNet-sirst3-test.py时出现以下报错，请问怎么解决
 raise TypeError('img should be PIL Image. Got {}'.format(type(img)))
TypeError: img should be PIL Image. Got <class 'torch.Tensor'>

**Comment by XinyiYing** [comment]
您好，通过描述无法清晰知道您的问题，可以将您遇到的问题的详细内容描述通过邮件yingxinyi18@nudt.edu.cn与我联系。
