### ISSUE TITLE
train.py test.py doesnt work as intented

### ISSUE THREAD

**Issue by karacanil** [XinyiYing/LESPS#14]
I cloned the repo, prepared the dataset as instructed and test.py and train.py doesn't work as intented. There are many syntax and logic errors in the code provided. The argument structure is almost totally wrong. If the README.md is not going to help us simulate your results and get started with your code what's the point? Is there a proper way to simulate your paper results or am I missing something here?

**Comment by XinyiYing** [comment]
We greatly appreciate your reply. We have downloaded our code and start it from the beginning to fix all bugs in the code. Again, very sorry for the inconvenience. For any questions regarding this paper, please feel free to contact me through emails (yingxinyi18@nudt.edu.cn).
