### ISSUE TITLE
训练自己数据集

### ISSUE THREAD

**Issue by Reginaii** [XinyiYing/LESPS#16]
作者，您好
mask img——idx代码，作者是否发布

**Comment by XinyiYing** [comment]
需要更详细的描述

**Comment by Reginaii** [comment]
训练自己数据集，需要准备mask，作者是否发布代码？

**Comment by XinyiYing** [comment]
是mask centroid和mask coarse吗？

**Comment by Reginaii** [comment]
训练自己数据集的全监督，关于mask图像生成 的代码

---- 回复的原邮件 ----
| 发件人 | Xinyi ***@***.***> |
| 发送日期 | 2024年01月10日 11:47 |
| 收件人 | XinyiYing/LESPS ***@***.***> |
| 抄送人 | Reginaii ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [XinyiYing/LESPS] 训练自己数据集 (Issue #16) |

是mask centroid和mask coarse吗？

**Comment by XinyiYing** [comment]
一般采集图像后，都是手工进行全监督标注的，也可以采用SAM的方式通过网络标注和人工矫正的多次迭代进行标注。

**Comment by Reginaii** [comment]
作者，您好，请问公开的数据集NUAA NUDT SIRST IRSDT等标注 ，在您公布的数据集中文件中，未找到，请问您是自己标注的嘛

---- 回复的原邮件 ----
| 发件人 | Xinyi ***@***.***> |
| 发送日期 | 2024年05月27日 11:12 |
| 收件人 | XinyiYing/LESPS ***@***.***> |
| 抄送人 | Reginaii ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [XinyiYing/LESPS] 训练自己数据集 (Issue #16) |

Closed #16 as completed.

**Comment by XinyiYing** [comment]
这些数据集的相关下载链接见[BasicIRSTD](https://github.com/XinyiYing/BasicIRSTD/)
