### ISSUE TITLE
Training the vanilla techniques

### ISSUE THREAD

**Issue by karacanil** [XinyiYing/LESPS#22]
Hello,
As far as I've seen the training code only works if we aim to analyze the results for LESPS coarse and centroid approaches. Is it possible to train the vanilla versions of ACM, ALCNet and DNANet for comparison purposes?
Thanks.

**Comment by XinyiYing** [comment]
We release the training code for train models under full supervision. See [train](https://github.com/XinyiYing/LESPS/blob/master/README.md#train) for details.
