### ISSUE TITLE
Problem with replicating the results

### ISSUE THREAD

**Issue by ketgg** [XinyiYing/LESPS#6]
Hi @XinyiYing,

Here are the steps we have done till now to run the code:
1) We cloned the repository
2) We trained it on the datasets and obtained various `.pth.tar` model files in `/log4` directory
3) While running the test we used `DNANet_LESPS_centroid_400.pth.tar` and `DNANet_LESPS_coarse_400.pth.tar` as arguments in test.py

However we noticed the results are not consistent with the `DNANet_LESPS_centroid.pth.tar` and `DNANet_LESPS_coarse.pth.tar` model files given in `/log` directory.

Also how to obtain `DNANet_full.pth.tar` model file present in `/log` directory during the training phase.

How to replicate the results?

**Comment by XinyiYing** [comment]
Sorry for late reply. We have fixed the small bugs (caused by version update) in our code.
