### ISSUE TITLE
不知道作者有没有遇到上下采样维度不匹配的问题

### ISSUE THREAD

**Issue by snailma0229** [XinyiYing/LESPS#8]
非常感谢您杰出的工作
不过我在复现代码的时候，遇到了RuntimeError: Sizes of tensors must match except in dimension 2. Got 210 and 211 (The offending index is 0)
经过debug发现，在维度为2^n的偶数的时候，不会出现问题
否则下采样再上采样在合并的时候就会出现维度不匹配的问题：比如211->105->210
不知道作者在运行的时候有没有遇到这样的问题

**Comment by ZZJDBB** [comment]
> 非常感谢您杰出的工作 不过我在复现代码的时候，遇到了RuntimeError: Sizes of tensors must match except in dimension 2. Got 210 and 211 (The offending index is 0) 经过debug发现，在维度为2^n的偶数的时候，不会出现问题 否则下采样再上采样在合并的时候就会出现维度不匹配的问题：比如211->105->210 不知道作者在运行的时候有没有遇到这样的问题

我也遇到了同样的问题，请问解决了吗

**Comment by XinyiYing** [comment]
您好，这个问题我在代码里做了相应的设置以确保输入图像的尺寸为32的倍数。
训练过程时通过设置train.py中的patchSize参数为下采样倍数的整数倍。patchSize控制随机裁剪的图像块的尺寸。
测试过程中是对输入图像进行zero padding，等过网络得到输出后再裁剪padding的部分。详情见dataset.py中85-88，121-123.
```
times = 32
img = np.pad(img, ((0, (h//times+1)*times-h),(0, (w//times+1)*times-w)), mode='constant')

**Comment by Laqcey** [comment]
> 非常感谢您杰出的工作 不过我在复现代码的时候，遇到了RuntimeError: Sizes of tensors must match except in dimension 2. Got 210 and 211 (The offending index is 0) 经过debug发现，在维度为2^n的偶数的时候，不会出现问题 否则下采样再上采样在合并的时候就会出现维度不匹配的问题：比如211->105->210 不知道作者在运行的时候有没有遇到这样的问题

我也遇到了这个问题，请问解决了吗

**Comment by Laqcey** [comment]
> 非常感谢您杰出的工作 不过我在复现代码的时候，遇到了RuntimeError： Sizes of tensors must match，维度 2 除外。得到 210 和 211（违规指数为 0） 经过debug发现，在维度为2^n的偶数的时候，不会出现问题 否则下采样再上采样在合并的时候就会出现维度不匹配的问题：比如211->105->210 不知道作者在运行的时候有没有遇到这样的问题

你好，请问你有出现这个问题吗：RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 197 but got size 196 for tensor number 1 in the list.

**Comment by sedulous6** [comment]
> > 非常感谢您杰出的工作 不过我在复现代码的时候，遇到了RuntimeError： Sizes of tensors must match，维度 2 除外。得到 210 和 211（违规指数为 0） 经过debug发现，在维度为2^n的偶数的时候，不会出现问题 否则下采样再上采样在合并的时候就会出现维度不匹配的问题：比如211->105->210 不知道作者在运行的时候有没有遇到这样的问题
> 
> 你好，请问你有出现这个问题吗：RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 197 but got size 196 for tensor number 1 in the list.

你解决了吗

**Comment by Laqcey** [comment]
> > > 非常感谢您杰出的工作 不过我在复现代码的时候，遇到了RuntimeError： Sizes of tensors must match，维度 2 除外。得到 210 和 211（违规指数为 0） 经过debug发现，在维度为2^n的偶数的时候，不会出现问题 否则下采样再上采样在合并的时候就会出现维度不匹配的问题：比如211->105->210 不知道作者在运行的时候有没有遇到这样的问题
> > 
> > 
> > 你好，请问你有出现这个问题吗：RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 197 but got size 196 for tensor number 1 in the list.
> 
> 你解决了吗

我还没有，你也出现这个问题了吗，或者你知道怎么解决吗

**Comment by Laqcey** [comment]
> 非常感谢您杰出的工作 不过我在复现代码的时候，遇到了RuntimeError： Sizes of tensors must match，维度 2 除外。得到 210 和 211（违规指数为 0） 经过debug发现，在维度为2^n的偶数的时候，不会出现问题 否则下采样再上采样在合并的时候就会出现维度不匹配的问题：比如211->105->210 不知道作者在运行的时候有没有遇到这样的问题

我也遇到了同样的问题，请问解决了吗

**Comment by Reginaii** [comment]
你好，请问这个问题怎么解决？

**Comment by Reginaii** [comment]
x0_1 = self.conv0_1(torch.cat([x0_0, self.up(x1_0)], 1))
RuntimeError: Sizes of tensors must match except in dimension 2. Got 210 and 211 (The offending index is 0)

**Comment by XinyiYing** [comment]
非常抱歉代码中的bug给大家带来的不便，上下不匹配的维度已在代码中修复，详情可参考[link](https://github.com/XinyiYing/LESPS/issues/8#issuecomment-1837698309)

**Comment by Reginaii** [comment]
你好，我想用我自己的数据集，关于mask 和img-idx 代码在哪呀

---- 回复的原邮件 ----
| 发件人 | Xinyi ***@***.***> |
| 发送日期 | 2024年01月05日 22:58 |
| 收件人 | XinyiYing/LESPS ***@***.***> |
| 抄送人 | Reginaii ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [XinyiYing/LESPS] 不知道作者有没有遇到上下采样维度不匹配的问题 (Issue #8) |

非常抱歉代码中的bug给大家带来的不便，上下不匹配的维度已在代码中修复，详情可参考link
